### ISSUE TITLE
Maintenance message can be unreadeable

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/maintenance-mode-wp#13]
Here are some screenshots with Maintenance Mode enabled on the latests default themes.

**Twenty Seventeen**: ok
![capture d ecran 2017-03-28 a 21 49 44](https://cloud.githubusercontent.com/assets/1521015/24424545/3b33f00c-1401-11e7-8426-86933f2ef254.png)

**Twenty Sixteen**: lack of constrast
![capture d ecran 2017-03-28 a 21 49 26](https://cloud.githubusercontent.com/assets/1521015/24424565/511ab162-1401-11e7-96dd-268e3c2d7b7e.png)

**Twenty Fifteen**: positioned behind another element
![capture d ecran 2017-03-28 a 21 49 10](https://cloud.githubusercontent.com/assets/1521015/24424600/69f5a480-1401-11e7-91a5-5c4c82e17b9e.png)

A simple way to solve the lack of readability would be to use a fullscreen container with a background color and a high z-index.

**Comment by trepmal** [comment]
#38 added some style improvements.

I'll close this and #15, but leave #19 for further consideration.

twentytwenty  
![twentytwenty](https://user-images.githubusercontent.com/251183/120725747-7fe2cb80-c48b-11eb-81c2-a52e53a4c564.png)

twentytwentyone  
![twentytwentyone](https://user-images.githubusercontent.com/251183/120725756-8113f880-c48b-11eb-9fee-47a92d142a9e.png)

twentyseventeen  
![twentyseventeen](https://user-images.githubusercontent.com/251183/120725759-81ac8f00-c48b-11eb-900f-62d4aad6629b.png)

twentyten
![twentyten](https://user-images.githubusercontent.com/251183/120725762-82452580-c48b-11eb-82de-b3a44a79ea8e.png)
