### ISSUE TITLE
Styles for the maintenance page

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/maintenance-mode-wp#14]
For now, the maintenance page doesn't look enough like a maintenance page.
I think the default template should be a bit more styled.

Here are some neutral examples that could inspire the styles for the maintenance page.

![capture d ecran 2017-03-28 a 22 55 33](https://cloud.githubusercontent.com/assets/1521015/24426974/aef64424-1409-11e7-96ad-97607f54569a.png)

![capture d ecran 2017-03-28 a 22 52 41](https://cloud.githubusercontent.com/assets/1521015/24426919/825a3cd6-1409-11e7-935e-496b8727d26a.png)

![maintenance_page-59575dad](https://cloud.githubusercontent.com/assets/1521015/24426951/9acad05a-1409-11e7-98fd-6c5dcb764cf0.jpg)

I prefer the latest (except the color which I find a bit aggressive): the message is very clear.

What are your thought on this?
Do you have some examples to share?

**Comment by GaryJones** [comment]
Since this has been open for 7 years with no action, and users can create whatever custom template they want anyway, I'm going to mark this as not planned.
