### ISSUE TITLE
REST API error code: 401 instead of 503

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/maintenance-mode-wp#20]
Actually, the error code is a `401`, meaning a client error (wrong authentication credentials).
I think it should be a `503` to describe a server error.

The error message could be also improved more descriptive, for example : _This site is under maintenance, the REST API access is currently restricted._ instead of _REST API access is currently restricted while we refresh things a bit._

**Comment by nielslange** [comment]
Closing this ticket as this issue had been fixed with https://github.com/Automattic/maintenance-mode-wp/pull/31.
