### ISSUE TITLE
undefined vip_maintenance_mode_maybe_restrict_rest_api

### ISSUE THREAD

**Issue by david-binda** [Automattic/maintenance-mode-wp#25]
```
 Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'vip_maintenance_mode_maybe_restrict_rest_api' not found or invalid function name
```

It should be `vip_maintenance_mode_restrict_rest_api`

**Comment by mattoperry** [comment]
Confirmed.  

This may cause issues when in maintenance mode with certain menu items.  For example, the Jetpack menu may fail a permissions check because of this.
