### ISSUE TITLE
Indicate that maintenance mode is enabled

### ISSUE THREAD

**Issue by benoitchantre** [Automattic/maintenance-mode-wp#3]
There's no hint that maintenance mode is enabled. You can easily forget to disable the plugin if you don't check the website in a private window.

I think something in the admin bar would be necessary.

**Comment by philipjohn** [comment]
Good idea! Wanna have a crack at that?

**Comment by benoitchantre** [comment]
I'll submit a PR.

**Comment by benoitchantre** [comment]
@philipjohn Here's the result of the first iteration.

![admin-bar-notice](https://cloud.githubusercontent.com/assets/1521015/23527404/19eebbb8-ff96-11e6-9900-44a796a41c11.png)

I plan to show it to users with `edit_posts` capability.

**Comment by philipjohn** [comment]
Nice :)

**Comment by benoitchantre** [comment]
I'll submit the PR once #10 is merged.
