### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by jenkoian** [Automattic/maintenance-mode-wp#34]
When using this plugin, there are a bunch of ajax warnings that appear, which [seems to have been fixed since the latest release](https://github.com/Automattic/maintenance-mode-wp/compare/0.2.1...master#diff-d730a1bb58dbb81da441e593dfc88f7cR138). 

It would be great if you could cut a new release so we could update the plugin and no longer see these ajax warnings. Thanks!

**Comment by GaryJones** [comment]
0.2.2 was tagged in August 2019 with the changes.
