### ISSUE TITLE
Enable via UI rather than code

### ISSUE THREAD

**Issue by varnent** [Automattic/maintenance-mode-wp#37]
Enabling and disabling via code is cumbersome and not very efficient or convenient for our needs. Would be much more ideal if this could be controlled from the admin dashboard.

**Comment by GaryJones** [comment]
The plugin can still be activated from the UI, but the use of the code constant is there to ensure that any activation is actually intended to put the site into maintenance mode i.e. a developer with GitHub write permissions needs to add the constant, and it's not just a click-happy wp-admin Administrator with access to the plugin page who activated it out of curiosity. Taking a site into maintenance mode is meant to have a little friction. 

You can of course leave the constant permanently defined in the code, and then use the existing plugin activation UI to turn it on and off.
